export const LOAD_GENRES_SUCCESS = "LOAD_GENRES_SUCCESS"

export const SET_TEXT_COLOR = "SET_TEXT_COLOR"

// #region movie actions
export const LOAD_NOW_PLAYING_MOVIE_SUCCESS = "LOAD_NOW_PLAYING_MOVIE_SUCCESS"
export const LOAD_RECOMMENDED_MOVIE_SUCCESS = "LOAD_RECOMMENDED_MOVIE_SUCCESS"
export const LOAD_POPULAR_MOVIE_SUCCESS = "LOAD_POPULAR_MOVIE_SUCCESS"
export const LOAD_TOP_RATED_MOVIE_SUCCESS = "LOAD_TOP_RATED_MOVIE_SUCCESS"

export const LOAD_NOW_PLAYING = "LOAD_NOW_PLAYING"
export const LOAD_LATEST_MOVIES = "LOAD_LATEST_MOVIES"
export const LOAD_TRENDING_MOVIES = "LOAD_TRENDING_MOVIES"

//#endregion